version: "3.7"

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /root/Caddyfile:/etc/caddy/Caddyfile
      - qbit-downloads:/srv
      - caddy-data:/data
      - caddy-config:/config

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - qbit-config:/config
      - qbit-downloads:/downloads
    network_mode: "host"
    restart: unless-stopped
    
volumes:
    qbit-downloads:
    qbit-config:
    caddy-config:
    caddy-data:
