version: "3.7"

services:
  caddy:
    image: caddy:latest
    container_name: caddy-reverse-proxy
    network_mode: "host"
    volumes:
      - /root/Caddyfile:/etc/caddy/Caddyfile
      - qbit-downloads:/srv
      - caddy-data:/data
      - caddy-config:/config
    restart: unless-stopped

  qbittorrent:
    image: p3terx/qbittorrent-enhanced:latest
    container_name: qbittorrent-enhanced
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - QBT_WEBUI_PORT=8080
      - UMASK_SET=022
    volumes:
      - qbit-config:/qBittorrent
      - qbit-downloads:/downloads
    network_mode: "host"
    restart: unless-stopped
    
volumes:
    qbit-downloads:
    qbit-config:
    caddy-config:
    caddy-data:
